services:
  db:
    image: postgres:18.0-alpine3.22
    env_file:
      - postgres.env
    # TODO: do not really need this for production
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data

