openapi: 3.1.0
info:
  title: Subscriptions Management API
  description: Simple API for managing service subscriptions
  version: 1.0.0
paths:
  /subscriptions:
    get:
      summary: Get all subscriptions
      description: Get all subscriptions
      responses:
        200:
          description: A list of subscriptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionWithId'
    post:
      summary: Create a subscription
      description: Create a subscription
      requestBody:
        description: Params of the new subscription
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionWithoutId'
      responses:
        201:
          description: A subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionWithId'
        422:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableBodyErrorMessage'
  /subscriptions/{subscriptionId}:
    get:
      summary: Get Subscription by ID
      description: Get a specific subscription by its ID in the system
      parameters:
        - in: path
          name: subscriptionId
          required: true
          schema:
            $ref: '#/components/schemas/SubscriptionId'
      responses:
        200:
          description: A subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionWithId'
        404:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorMessage'
        422:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessablePathErrorMessage'
    put:
      summary: Update Subscription
      description: Update a specific subscription (defined by its ID in the system)
      parameters:
        - in: path
          name: subscriptionId
          required: true
          schema:
            $ref: '#/components/schemas/SubscriptionId'
      requestBody:
        description: Params of the new subscription
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionWithoutId'
      responses:
        200:
          description: A subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionWithId'
        404:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorMessage'
        422:
          description: Error message
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/UnprocessableBodyErrorMessage'
                - $ref: '#/components/schemas/UnprocessablePathErrorMessage'
    delete:
      summary: Delete Subscription
      description: Delete a specific subscription (defined by its ID in the system)
      parameters:
        - in: path
          name: subscriptionId
          required: true
          schema:
            $ref: '#/components/schemas/SubscriptionId'
      responses:
        204:
          description: Subscription deleted successfully
        404:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorMessage'
        422:
          description: Error message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessablePathErrorMessage'
components:
  schemas:
    SubscriptionId:
      type: integer
      description: Unique identifier of the subscription
      example: 1
    SubscriptionWithId:
      allOf:
        - $ref: '#/components/schemas/SubscriptionWithoutId'
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/SubscriptionId'
          required:
            - id
    SubscriptionWithoutId:
      type: object
      properties:
        service_name:
          type: string
          description: "The subscription's service name"
          example: 'Yandex Plus'
        price:
          type: integer
          description: The monthly fee for the subscription
          example: 400
        user_id:
          type: string
          format: uuid
          description: ID of the subscriber
        start_date:
          type: string
          format: '^\d{2}-\d{4}$'
          description: The first month of the subscription (in format MM-YYYY)
          example: 01-2012
        end_date:
          type: string
          format: '^\d{2}-\d{4}$'
          description: The last month of the subscription (in format MM-YYYY)
          example: 12-2012
      required:
        - service_name
        - price
        - user_id
        - start_date
    NotFoundErrorMessage:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: not found
      required:
        - error
    UnprocessableBodyErrorMessage:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: malformed body
      required:
        - error
    UnprocessablePathErrorMessage:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: malformed path
      required:
        - error
