openapi: 3.1.0
info:
  title: Subscriptions Management API
  description: Simple API for managing service subscriptions
  version: 1.0.0
paths:
  /subscriptions:
    get:
      summary: Get all subscriptions
      description: Get all subscriptions
      responses:
        200:
          description: A list of subscriptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionWithId'
components:
  schemas:
    SubscriptionWithId:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier of the subscription
        service_name:
          type: string
          description: "The subscription's service name"
          example: 'Yandex Plus'
      required:
        - id
        - service_name
